# Generated by Django 4.0 on 2023-04-07 09:55

from django.db import migrations, models
import django.db.models.deletion
import profiles.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', profiles.encrypted_fields.EncryptedCharField(max_length=255)),
                ('last_name', profiles.encrypted_fields.EncryptedCharField(max_length=255)),
                ('phone_number', profiles.encrypted_fields.EncryptedCharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
